export const estimateTemplates = [
  {
    id: "basic-remodel",
    title: "Basic Home Remodel",
    description: "A simple residential remodeling project",
    category: "Residential",
    items: [
      {
        id: "demo",
        description: "Demolition and debris removal",
        quantity: 1,
        unit: "lot",
        rate: 1500,
      },
      {
        id: "framing",
        description: "Framing materials and labor",
        quantity: 1,
        unit: "lot",
        rate: 3200,
      },
      {
        id: "drywall",
        description: "Drywall installation and finishing",
        quantity: 650,
        unit: "sq ft",
        rate: 2.5,
      },
      {
        id: "paint",
        description: "Interior painting (walls and ceiling)",
        quantity: 650,
        unit: "sq ft",
        rate: 1.75,
      },
      {
        id: "flooring",
        description: "Engineered hardwood flooring",
        quantity: 500,
        unit: "sq ft",
        rate: 8.5,
      },
      {
        id: "trim",
        description: "Trim and baseboards installation",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 350,
      },
    ],
  },
  {
    id: "small-bathroom",
    title: "Small Bathroom Renovation",
    description: "Complete bathroom renovation for a small bathroom",
    category: "Residential",
    items: [
      {
        id: "demo",
        description: "Demolition and debris removal",
        quantity: 1,
        unit: "lot",
        rate: 850,
      },
      {
        id: "plumbing",
        description: "Plumbing rough-in and fixtures",
        quantity: 1,
        unit: "lot",
        rate: 1800,
      },
      {
        id: "electrical",
        description: "Electrical work and fixtures",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "drywall",
        description: "Drywall installation and finishing",
        quantity: 180,
        unit: "sq ft",
        rate: 2.75,
      },
      {
        id: "tile",
        description: "Floor and shower tile installation",
        quantity: 120,
        unit: "sq ft",
        rate: 15,
      },
      {
        id: "vanity",
        description: "Vanity installation",
        quantity: 1,
        unit: "ea",
        rate: 800,
      },
      {
        id: "toilet",
        description: "Toilet installation",
        quantity: 1,
        unit: "ea",
        rate: 450,
      },
      {
        id: "shower",
        description: "Shower door installation",
        quantity: 1,
        unit: "ea",
        rate: 650,
      },
      {
        id: "paint",
        description: "Interior painting",
        quantity: 180,
        unit: "sq ft",
        rate: 1.75,
      },
      {
        id: "accessories",
        description: "Bathroom accessories installation",
        quantity: 1,
        unit: "lot",
        rate: 250,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 200,
      },
    ],
  },
  {
    id: "fence-installation",
    title: "Fence Installation",
    description: "Wood privacy fence installation",
    category: "Outdoor",
    items: [
      {
        id: "materials",
        description: "Wood fence materials (posts, rails, pickets)",
        quantity: 100,
        unit: "ft",
        rate: 18.5,
      },
      {
        id: "labor",
        description: "Installation labor",
        quantity: 100,
        unit: "ft",
        rate: 12,
      },
      {
        id: "concrete",
        description: "Concrete for post setting",
        quantity: 20,
        unit: "ea",
        rate: 8.5,
      },
      {
        id: "gate",
        description: "Gate installation and hardware",
        quantity: 1,
        unit: "ea",
        rate: 350,
      },
      {
        id: "cleanup",
        description: "Site cleanup and debris removal",
        quantity: 1,
        unit: "lot",
        rate: 250,
      },
    ],
  },
  {
    id: "commercial-office",
    title: "Commercial Office Renovation",
    description: "Basic office space renovation",
    category: "Commercial",
    items: [
      {
        id: "demo",
        description: "Demolition and debris removal",
        quantity: 1,
        unit: "lot",
        rate: 2200,
      },
      {
        id: "framing",
        description: "Framing for new walls",
        quantity: 120,
        unit: "ft",
        rate: 28,
      },
      {
        id: "drywall",
        description: "Drywall installation and finishing",
        quantity: 1200,
        unit: "sq ft",
        rate: 2.5,
      },
      {
        id: "electrical",
        description: "Electrical work and fixtures",
        quantity: 1,
        unit: "lot",
        rate: 3500,
      },
      {
        id: "doors",
        description: "Interior doors and hardware",
        quantity: 4,
        unit: "ea",
        rate: 350,
      },
      {
        id: "paint",
        description: "Interior painting",
        quantity: 1200,
        unit: "sq ft",
        rate: 1.5,
      },
      {
        id: "flooring",
        description: "Commercial grade carpet installation",
        quantity: 800,
        unit: "sq ft",
        rate: 4.75,
      },
      {
        id: "ceiling",
        description: "Drop ceiling installation",
        quantity: 800,
        unit: "sq ft",
        rate: 3.5,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 450,
      },
    ],
  },
  {
    id: "kitchen-remodel",
    title: "Kitchen Remodeling",
    description: "Complete kitchen renovation project",
    category: "Residential",
    items: [
      {
        id: "demo",
        description: "Demolition and debris removal",
        quantity: 1,
        unit: "lot",
        rate: 1800,
      },
      {
        id: "plumbing",
        description: "Plumbing rough-in and fixtures",
        quantity: 1,
        unit: "lot",
        rate: 2200,
      },
      {
        id: "electrical",
        description: "Electrical work including lighting",
        quantity: 1,
        unit: "lot",
        rate: 2400,
      },
      {
        id: "cabinets",
        description: "Custom cabinets supply and install",
        quantity: 20,
        unit: "ln ft",
        rate: 350,
      },
      {
        id: "countertop",
        description: "Quartz countertop supply and install",
        quantity: 30,
        unit: "sq ft",
        rate: 85,
      },
      {
        id: "backsplash",
        description: "Ceramic tile backsplash",
        quantity: 35,
        unit: "sq ft",
        rate: 22,
      },
      {
        id: "flooring",
        description: "Tile flooring installation",
        quantity: 200,
        unit: "sq ft",
        rate: 16,
      },
      {
        id: "appliances",
        description: "Appliance installation",
        quantity: 5,
        unit: "ea",
        rate: 250,
      },
      {
        id: "paint",
        description: "Interior painting",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 350,
      },
    ],
  },
  {
    id: "deck-construction",
    title: "Deck Construction",
    description: "Wooden deck building project",
    category: "Outdoor",
    items: [
      {
        id: "permits",
        description: "Building permits and inspections",
        quantity: 1,
        unit: "lot",
        rate: 500,
      },
      {
        id: "excavation",
        description: "Excavation and footings",
        quantity: 12,
        unit: "ea",
        rate: 125,
      },
      {
        id: "framing",
        description: "Pressure-treated lumber framing",
        quantity: 400,
        unit: "sq ft",
        rate: 12,
      },
      {
        id: "decking",
        description: "Composite decking material and installation",
        quantity: 400,
        unit: "sq ft",
        rate: 22,
      },
      {
        id: "railing",
        description: "Railing system installation",
        quantity: 60,
        unit: "ln ft",
        rate: 65,
      },
      {
        id: "stairs",
        description: "Stair construction",
        quantity: 1,
        unit: "ea",
        rate: 1200,
      },
      {
        id: "cleanup",
        description: "Site cleanup and debris removal",
        quantity: 1,
        unit: "lot",
        rate: 350,
      },
    ],
  },
  {
    id: "basement-finish",
    title: "Basement Finishing",
    description: "Complete basement finishing project",
    category: "Residential",
    items: [
      {
        id: "permits",
        description: "Building permits and inspections",
        quantity: 1,
        unit: "lot",
        rate: 750,
      },
      {
        id: "framing",
        description: "Wall framing and insulation",
        quantity: 600,
        unit: "sq ft",
        rate: 8.5,
      },
      {
        id: "electrical",
        description: "Electrical work including lighting",
        quantity: 1,
        unit: "lot",
        rate: 3200,
      },
      {
        id: "plumbing",
        description: "Plumbing rough-in for bathroom",
        quantity: 1,
        unit: "lot",
        rate: 2800,
      },
      {
        id: "drywall",
        description: "Drywall installation and finishing",
        quantity: 1800,
        unit: "sq ft",
        rate: 2.75,
      },
      {
        id: "flooring",
        description: "Carpet and vinyl flooring",
        quantity: 800,
        unit: "sq ft",
        rate: 6.5,
      },
      {
        id: "bathroom",
        description: "Basement bathroom installation",
        quantity: 1,
        unit: "lot",
        rate: 5500,
      },
      {
        id: "doors",
        description: "Interior doors and trim",
        quantity: 5,
        unit: "ea",
        rate: 320,
      },
      {
        id: "paint",
        description: "Interior painting",
        quantity: 1800,
        unit: "sq ft",
        rate: 1.8,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 450,
      },
    ],
  },
  {
    id: "hvac-installation",
    title: "HVAC Installation",
    description: "New HVAC system installation",
    category: "HVAC",
    items: [
      {
        id: "permits",
        description: "Permits and inspections",
        quantity: 1,
        unit: "lot",
        rate: 650,
      },
      {
        id: "equipment",
        description: "HVAC equipment (furnace and AC)",
        quantity: 1,
        unit: "set",
        rate: 5200,
      },
      {
        id: "ductwork",
        description: "Ductwork installation and materials",
        quantity: 1,
        unit: "lot",
        rate: 3800,
      },
      {
        id: "electrical",
        description: "Electrical connections and wiring",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "thermostat",
        description: "Smart thermostat installation",
        quantity: 1,
        unit: "ea",
        rate: 350,
      },
      {
        id: "testing",
        description: "System testing and balancing",
        quantity: 1,
        unit: "lot",
        rate: 450,
      },
      {
        id: "removal",
        description: "Old system removal and disposal",
        quantity: 1,
        unit: "lot",
        rate: 650,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 250,
      },
    ],
  },
  {
    id: "hvac-service",
    title: "HVAC Service & Maintenance",
    description: "Regular HVAC service and maintenance",
    category: "HVAC",
    items: [
      {
        id: "inspection",
        description: "Complete system inspection",
        quantity: 1,
        unit: "ea",
        rate: 150,
      },
      {
        id: "filter",
        description: "Replace air filters",
        quantity: 2,
        unit: "ea",
        rate: 35,
      },
      {
        id: "coil",
        description: "Clean evaporator and condenser coils",
        quantity: 1,
        unit: "set",
        rate: 175,
      },
      {
        id: "refrigerant",
        description: "Check and adjust refrigerant levels",
        quantity: 1,
        unit: "ea",
        rate: 85,
      },
      {
        id: "ductwork",
        description: "Inspect and seal ductwork",
        quantity: 1,
        unit: "lot",
        rate: 120,
      },
      {
        id: "components",
        description: "Lubricate moving components",
        quantity: 1,
        unit: "lot",
        rate: 65,
      },
      {
        id: "thermostat",
        description: "Calibrate thermostat",
        quantity: 1,
        unit: "ea",
        rate: 45,
      },
      {
        id: "testing",
        description: "Test system cycles and performance",
        quantity: 1,
        unit: "ea",
        rate: 75,
      },
    ],
  },
  {
    id: "interior-painting",
    title: "Interior Painting",
    description: "Complete interior house painting",
    category: "Painting",
    items: [
      {
        id: "prep",
        description: "Surface preparation and repairs",
        quantity: 1500,
        unit: "sq ft",
        rate: 0.75,
      },
      {
        id: "primer",
        description: "Primer application",
        quantity: 1500,
        unit: "sq ft",
        rate: 0.65,
      },
      {
        id: "walls",
        description: "Wall painting (2 coats)",
        quantity: 1200,
        unit: "sq ft",
        rate: 1.25,
      },
      {
        id: "ceiling",
        description: "Ceiling painting",
        quantity: 800,
        unit: "sq ft",
        rate: 1.35,
      },
      {
        id: "trim",
        description: "Trim and door painting",
        quantity: 1,
        unit: "lot",
        rate: 850,
      },
      {
        id: "cleanup",
        description: "Cleanup and touch-ups",
        quantity: 1,
        unit: "lot",
        rate: 350,
      },
      {
        id: "materials",
        description: "Premium paint and supplies",
        quantity: 1,
        unit: "lot",
        rate: 950,
      },
    ],
  },
  {
    id: "exterior-painting",
    title: "Exterior Painting",
    description: "Complete exterior house painting",
    category: "Painting",
    items: [
      {
        id: "prep",
        description: "Pressure washing and surface preparation",
        quantity: 2000,
        unit: "sq ft",
        rate: 0.85,
      },
      {
        id: "repairs",
        description: "Wood repairs and replacements",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "caulking",
        description: "Caulking and sealing",
        quantity: 1,
        unit: "lot",
        rate: 750,
      },
      {
        id: "primer",
        description: "Exterior primer application",
        quantity: 2000,
        unit: "sq ft",
        rate: 0.75,
      },
      {
        id: "paint",
        description: "Exterior paint application (2 coats)",
        quantity: 2000,
        unit: "sq ft",
        rate: 1.45,
      },
      {
        id: "trim",
        description: "Trim and accent painting",
        quantity: 1,
        unit: "lot",
        rate: 950,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 450,
      },
      {
        id: "materials",
        description: "Premium exterior paint and supplies",
        quantity: 1,
        unit: "lot",
        rate: 1250,
      },
    ],
  },
  {
    id: "landscape-design",
    title: "Landscape Design & Installation",
    description: "Complete landscape renovation",
    category: "Landscaping",
    items: [
      {
        id: "design",
        description: "Landscape design and planning",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "demo",
        description: "Demolition and site preparation",
        quantity: 1000,
        unit: "sq ft",
        rate: 1.75,
      },
      {
        id: "grading",
        description: "Grading and drainage solutions",
        quantity: 1000,
        unit: "sq ft",
        rate: 2.25,
      },
      {
        id: "irrigation",
        description: "Irrigation system installation",
        quantity: 1,
        unit: "lot",
        rate: 2800,
      },
      {
        id: "sod",
        description: "Sod installation",
        quantity: 800,
        unit: "sq ft",
        rate: 1.95,
      },
      {
        id: "plants",
        description: "Trees, shrubs, and plants",
        quantity: 1,
        unit: "lot",
        rate: 3500,
      },
      {
        id: "mulch",
        description: "Mulch and decorative rock",
        quantity: 1,
        unit: "lot",
        rate: 1200,
      },
      {
        id: "hardscape",
        description: "Hardscaping (pavers, retaining wall)",
        quantity: 1,
        unit: "lot",
        rate: 4500,
      },
      {
        id: "lighting",
        description: "Landscape lighting",
        quantity: 1,
        unit: "lot",
        rate: 1800,
      },
      {
        id: "cleanup",
        description: "Final cleanup",
        quantity: 1,
        unit: "lot",
        rate: 450,
      },
    ],
  },
  {
    id: "lawn-maintenance",
    title: "Lawn Maintenance",
    description: "Regular lawn care service (monthly)",
    category: "Landscaping",
    items: [
      {
        id: "mowing",
        description: "Lawn mowing and edging (4 visits)",
        quantity: 4,
        unit: "visit",
        rate: 75,
      },
      {
        id: "trimming",
        description: "Shrub and hedge trimming",
        quantity: 1,
        unit: "lot",
        rate: 150,
      },
      {
        id: "weeding",
        description: "Flower bed weeding",
        quantity: 4,
        unit: "visit",
        rate: 65,
      },
      {
        id: "fertilization",
        description: "Lawn fertilization",
        quantity: 1,
        unit: "ea",
        rate: 120,
      },
      {
        id: "pestcontrol",
        description: "Pest control application",
        quantity: 1,
        unit: "ea",
        rate: 95,
      },
      {
        id: "cleanup",
        description: "Debris removal and cleanup",
        quantity: 4,
        unit: "visit",
        rate: 45,
      },
    ],
  },
];
