<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/1999/xhtml"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>Sitemap Index</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            font-size: 14px;
            color: #333;
            margin: 0;
            padding: 0;
            background: #f5f7fa;
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px 20px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
          }
          .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 0 20px;
          }
          h1 {
            margin: 0 0 10px 0;
            font-size: 32px;
            font-weight: 600;
          }
          .intro {
            opacity: 0.95;
            margin: 0;
            line-height: 1.6;
          }
          .stats {
            background: white;
            margin: 30px auto;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            max-width: 1400px;
          }
          .stats-inner {
            display: flex;
            align-items: center;
            gap: 10px;
          }
          .stats-icon {
            font-size: 24px;
          }
          .stats-text {
            color: #667eea;
            font-weight: 600;
            font-size: 16px;
          }
          .content {
            background: white;
            margin: 0 auto 30px;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            max-width: 1400px;
          }
          .sitemap-list {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));
            gap: 20px;
            margin-top: 20px;
          }
          .sitemap-card {
            background: #f9fafb;
            border: 1px solid #e5e7eb;
            border-radius: 8px;
            padding: 20px;
            transition: all 0.3s ease;
          }
          .sitemap-card:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(102, 126, 234, 0.15);
            border-color: #667eea;
          }
          .sitemap-card a {
            color: #667eea;
            text-decoration: none;
            font-weight: 600;
            font-size: 15px;
            display: block;
            margin-bottom: 8px;
            word-break: break-all;
          }
          .sitemap-card a:hover {
            color: #764ba2;
          }
          .sitemap-meta {
            color: #6b7280;
            font-size: 12px;
            display: flex;
            align-items: center;
            gap: 5px;
          }
          .footer {
            text-align: center;
            padding: 20px;
            color: #6b7280;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="container">
            <h1>📑 Sitemap Index</h1>
            <p class="intro">
              This is the main sitemap index containing links to all sub-sitemaps for this website.
            </p>
          </div>
        </div>
        
        <div class="container">
          <div class="stats">
            <div class="stats-inner">
              <span class="stats-icon">📊</span>
              <span class="stats-text">
                Total Sitemaps: <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/>
              </span>
            </div>
          </div>
          
          <div class="content">
            <div class="sitemap-list">
              <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                <div class="sitemap-card">
                  <a href="{sitemap:loc}">
                    <xsl:value-of select="sitemap:loc"/>
                  </a>
                  <div class="sitemap-meta">
                    <span>📅</span>
                    <span>Last updated: <xsl:value-of select="substring(sitemap:lastmod, 1, 10)"/></span>
                  </div>
                </div>
              </xsl:for-each>
            </div>
          </div>
        </div>
        
        <div class="footer">
          Generated by Contractor+ | Last updated: <xsl:value-of select="substring(sitemap:sitemapindex/sitemap:sitemap[1]/sitemap:lastmod, 1, 10)"/>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>