import {
  AssetIcon,
  BigChiefAIIcon,
  BookkeepingIcon,
  ClientIcon,
  EstimatesIcon,
  EstimaticIcon,
  FieldServiceIcon,
  InvoicingIcon,
  LeadGenerationIcon,
  PaymentsIcon,
  PROIcon,
  ProjectIcon,
  PropertyIcon,
  ReportingIcon,
  SchedulingIcon,
  ServiceIcon,
  TelephoneIcon,
  TimeIcon,
  TrackingIcon,
  TrophyIcon,
} from "./Icons";

export const menuItems = [
  {
    id: "whycontractor",
    label: "Why Contractor+?",
  },
  { id: "features", label: "Features" },
  { id: "industries", label: "Industries" },
  { id: "pricing", label: "Pricing" },
  { id: "resources", label: "Resources" },
];
export const featureLinkslinks = [
  {
    label: "CRM",
    description: "Manage Leads & Clients Effortlessly",
    href: "/",
    icon: <ServiceIcon />,
  },
  {
    label: "Estimates & Quotes",
    description: "Organize Jobs, Teams & Real-Time Updates",
    href: "/",
    icon: <EstimatesIcon />,
  },
  {
    label: "Mileage Tracking",
    description: "Simplify Projects, Timelines & Tasks Easily",
    href: "/",
    icon: <TrackingIcon />,
  },
  {
    label: "Field Service Management",
    description: "Smart & Accurate, Winning Project Estimations",
    href: "/",
    icon: <FieldServiceIcon />,
  },
  {
    label: "Deal Flow Tracking",
    description: "Real-Time Insights for Smarter Decisions",
    href: "/",
    icon: <TrophyIcon />,
  },
  {
    label: "Asset Tracking",
    description: "Find More Customers To Grow Your Business",
    href: "/",
    icon: <AssetIcon />,
  },
  {
    label: "Project Management",
    description: "Organize Finances, Simplify Your Accounting",
    href: "/",
    icon: <ProjectIcon />,
  },
  {
    label: "Scheduling",
    description: "Organize Finances, Simplify Your Accounting",
    icon: <SchedulingIcon />,
    href: "/",
  },
  {
    label: "Reporting",
    description: "Fast, Accurate, Winning Bids Made Easy",
    href: "/",
    icon: <ReportingIcon />,
  },
  {
    label: "Estimatic AI",
    description: "Visualize Your Sales Sales Pipeline",
    href: "/",
    icon: <EstimaticIcon />,
  },
  {
    label: "Client Portal",
    description: "Optimize Team Efficiency & Job Assignments",
    href: "/",
    icon: <ClientIcon />,
  },
  {
    label: "PRO Website",
    description: "Simple, Secure Project Access for Clients",
    href: "/",
    icon: <PROIcon />,
  },
  {
    label: "Big Chief AI",
    description: "Automate Invoicing & Get Paid Faster",
    href: "/",
    icon: <BigChiefAIIcon />,
  },
  {
    label: "Invoicing & Collections",
    description: "Centralized Team & Client Conversations",
    href: "/",
    icon: <InvoicingIcon />,
  },
  {
    label: "Payments",
    description: "GPS Verified Time Tracking For The Whole Team",
    href: "/",
    icon: <PaymentsIcon />,
  },
  {
    label: "Lead Generation",
    description: "Automatically Track & Maximize Mileage Deductions",
    href: "/",
    icon: <LeadGenerationIcon />,
  },
  {
    label: "Two-Way Communication",
    description: "Monitor Equipment, Prevent Costly Losses",
    href: "/",
    icon: <TelephoneIcon />,
  },
  {
    label: "Property Profiles",
    description: "Insights to Boost Efficiency & Profits",
    href: "/",
    icon: <PropertyIcon />,
  },
  {
    label: "Bookkeeping",
    description: "Showcase Your Business & Attract Customers",
    href: "/",
    icon: <BookkeepingIcon />,
  },
  {
    label: "Time Clock",
    description: "Online, In-person, QR & ACH + Instant payouts!",
    href: "/",
    icon: <TimeIcon />,
  },
];
export const IndustriesDropdownLinks = [
  { label: "General Contractor", href: "/" },
  { label: "Plumbing", href: "/" },
  { label: "Construction", href: "/" },
  { label: "HVAC", href: "/" },
  { label: "Remodeling", href: "/" },
  { label: "Painting", href: "/" },
  { label: "Roofing", href: "/" },
  { label: "Junk Removal", href: "/" },
  { label: "Locksmith", href: "/" },
  { label: "Tiling", href: "/" },
  { label: "Drywall", href: "/" },
  { label: "Mechanical", href: "/" },
  { label: "Cleaning", href: "/" },
  { label: "Restoration", href: "/" },
  { label: "Electrician", href: "/" },
  { label: "Fence", href: "/" },
  { label: "Flooring", href: "/" },
  { label: "Pest Control", href: "/" },
  { label: "Pool & Spa", href: "/" },
  { label: "Tree Care", href: "/" },
  { label: "Landscaping", href: "/" },
  { label: "Snow Removal", href: "/" },
  { label: "Lawn Care", href: "/" },
  { label: "Paving", href: "/" },
  { label: "Solar", href: "/" },
  { label: "Janitorial", href: "/" },
  { label: "Irrigation", href: "/" },
  { label: "Pressure Washing", href: "/" },
  { label: "Property Maintenance", href: "/" },
  { label: "Window Cleaning", href: "/" },
  { label: "Carpentry", href: "/" },
  { label: "Carpet Cleaning", href: "/" },
  { label: "Chimney Sweeping", href: "/" },
  { label: "Elevator", href: "/" },
  { label: "Excavation", href: "/" },
  { label: "Garage Door", href: "/" },
  { label: "Handyman", href: "/" },
  { label: "Septic & Pump", href: "/" },
  { label: "Small Engine Repair", href: "/" },
];
export const WhyContractorDropdownlinks = [
  {
    label: "CRM",
    description: "Manage Leads & Clients Effortlessly",
    href: "/",
  },
  {
    label: "Field Service Management",
    description: "Organize Jobs, Teams & Real-Time Updates",
    href: "/",
  },
  {
    label: "Project Management",
    description: "Simplify Projects, Timelines & Tasks Easily",
    href: "/",
  },
  {
    label: "Estimate AI",
    description: "Smart & Accurate, Winning Project Estimations",
    href: "/",
  },
  {
    label: "Bid Cloud AI",
    description: "Real-Time Insights for Smarter Decisions",
    href: "/",
  },
  {
    label: "Lead Generation",
    description: "Find More Customers To Grow Your Business",
    href: "/",
  },
  {
    label: "Bookkeeping",
    description: "Organize Finances, Simplify Your Accounting",
    href: "/",
  },
  { label: "Features", description: "", href: "/" },
  {
    label: "Estimates & Quotes",
    description: "Fast, Accurate, Winning Bids Made Easy",
    href: "/",
  },
  {
    label: "Deal Flow Tracking",
    description: "Visualize Your Sales Sales Pipeline",
    href: "/",
  },
  {
    label: "Scheduling",
    description: "Optimize Team Efficiency & Job Assignments",
    href: "/",
  },
  {
    label: "Client Portal",
    description: "Simple, Secure Project Access for Clients",
    href: "/",
  },
  {
    label: "Invoicing & Collections",
    description: "Automate Invoicing & Get Paid Faster",
    href: "/",
  },
  {
    label: "Two-Way Communications",
    description: "Centralized Team & Client Conversations",
    href: "/",
  },
  {
    label: "Time Clock",
    description: "GPS Verified Time Tracking For The Whole Team",
    href: "/",
  },
  {
    label: "Mileage Tracking",
    description: "Automatically Track & Maximize Mileage Deductions",
    href: "/",
  },
  {
    label: "Asset Tracking",
    description: "Monitor Equipment, Prevent Costly Losses",
    href: "/",
  },
  {
    label: "Reporting",
    description: "Insights to Boost Efficiency & Profits",
    href: "/",
  },
  {
    label: "PRO Website",
    description: "Showcase Your Business & Attract Customers",
    href: "/",
  },
  {
    label: "Payments",
    description: "Online, In-person, QR & ACH + Instant payouts!",
    href: "/",
  },
  {
    label: "Property Profiles",
    description: "Remember Your Property Maintenance",
    href: "/",
  },
];
export const ResourcesDropdownlinks = [
  { label: "Contractor+ Blog", href: "/" },
  { label: "Industry Events", href: "/" },
  { label: "Hard Hat Chat", href: "/" },
  { label: "Mindset Monday", href: "/" },
  { label: "Supply Partner Program", href: "/" },
  { label: "The Owners Perspective", href: "/" },
  { label: "Features Roadmap", href: "/" },
  { label: "Free Tools & Templates", href: "/" },
  { label: "Support Center", href: "/" },
  { label: "Regional Labor Pricing", href: "/" },
  { label: "Regional Material Pricing", href: "/" },
];
export const PricingDropdownLinks = [
  { label: "Contractor+ Blog", href: "/" },
  { label: "Industry Events", href: "/" },
  { label: "Hard Hat Chat", href: "/" },
  { label: "Mindset Monday", href: "/" },
  { label: "Supply Partner Program", href: "/" },
  { label: "The Owners Perspective", href: "/" },
  { label: "Features Roadmap", href: "/" },
  { label: "Free Tools & Templates", href: "/" },
  { label: "Support Center", href: "/" },
  { label: "Regional Labor Pricing", href: "/" },
  { label: "Regional Material Pricing", href: "/" },
];
